version: "1.0"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    networks:
      - my-network

  db:
    container_name: postgres_category
    image: postgres:alpine3.19
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", 'psql', '-U', "root", 'main' ]
      timeout: 2s
      retries: 5
    volumes:
      - data-vol:/data/db

  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - my-network
volumes:
  app:
  data-vol:

networks:
  my-network:
    driver: bridge